services:
  - type: web
    name: puppeteer-app
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    branch: main
    plan: free
    autoDeploy: true
    
