services:
  - type: web
    name: project
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    docker:
      baseImage: render/node:18
      args:
        - --no-sandbox
